export OPENAI_API_KEY="op://Private/OpenAI/API_KEY"
export ANTHROPIC_API_KEY="op://Private/Anthropic/API_KEY"
export TAVILY_API_KEY="op://Private/Tavily/API_KEY"
export GROQ_API_KEY="op://Private/Groq/API_KEY"
export DEEPSEEK_API_KEY="op://Secret/DeepSeek/API_KEY"
export GEMINI_API_KEY="op://Private/Gemini/API_KEY"
