#!/bin/bash

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# yabai -m signal --add event=window_created action="$HOME/.config/yabai/scripts/apply_layout.sh"
# yabai -m signal --add event=window_destroyed action="$HOME/.config/yabai/scripts/apply_layout.sh"

yabai -m config external_bar all:0:0 \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement second_child \
    window_shadow float \
    window_opacity on \
    window_opacity_duration 0.25 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.90 \
    window_animation_duration 0.25 \
    window_animation_easing ease_out_quint \
    insert_feedback_color 0xff9dd274 \
    split_ratio 0.50 \
    auto_balance off \
    mouse_modifier alt \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action stack \
    \
    top_padding 10 \
    bottom_padding 10 \
    left_padding 10 \
    right_padding 10 \
    window_gap 14

# Turn off tiling by default for all apps
yabai -m rule --add app=".*" manage=off

# Manage only specific apps by default
# Set sub-layer to normal
yabai -m rule --add app="^(Ghostty|Linear|Obsidian|Discord|Tinkerwell|Table Plus)$" manage=on

# Set default sub-layer for all apps
# yabai -m rule --add app=".*" sub-layer=normal

# Set default layout
yabai -m config layout bsp

echo "yabai configuration loaded..."

# Start borders
# borders
