"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 1000

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true
style = "fg:peach"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:peach"
style_root = "fg:peach"
format = '[ $user ]($style)'

[directory]
style = "fg:yellow"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"

[git_branch]
symbol = ""
style = "fg:lavender"
format = '[[ $symbol $branch ](fg:lavender)]($style)'

[git_status]
style = "fg:lavender"
format = '[[($all_status$ahead_behind )](fg:lavender)]($style)'

[nodejs]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[c]
symbol = " "
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[rust]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[golang]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[php]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[java]
symbol = " "
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[kotlin]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[haskell]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[python]
symbol = ""
style = "fg:sky"
format = '[[ $symbol( $version) ](fg:sky)]($style)'

[docker_context]
symbol = ""
style = "fg:overlay1"
format = '[[ $symbol( $context) ](fg:overlay1)]($style)'

[conda]
style = "fg:overlay1"
format = '[[ $symbol( $environment) ](fg:overlay1)]($style)'

[time]
disabled = true
time_format = "%R"
style = "fg:overlay2"
format = '[[  $time ](fg:overlay2)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:lavender)'
vimcmd_replace_symbol = '[](bold fg:lavender)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
